# Generated by Django 5.0.4 on 2024-04-06 17:18

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=456, verbose_name='State')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=455, unique=True, verbose_name='Email id')),
                ('password', models.CharField(blank=True, max_length=456, null=True, verbose_name='Password')),
                ('user_name', models.CharField(max_length=455, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=455, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=455, null=True, verbose_name='Second Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('contact_no', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Contact No')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Contact No')),
                ('otp', models.IntegerField(blank=True, null=True, verbose_name='Contact No')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Odyssey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Odyssey Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Odyssey End Date')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('destination_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odysseies_to_places', related_query_name='odyssey_to_place', to='web_app.state', verbose_name="Odyssey's end place")),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odysseies_from_places', related_query_name='odyssey_from_place', to='web_app.state', verbose_name="Odyssey's start place")),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odysseies_organiser', related_query_name='odyssey_organiser', to='web_app.user', verbose_name='Organiser')),
                ('user', models.ManyToManyField(related_name='odysseies', related_query_name='odyssey', to='web_app.user', verbose_name='Travellers')),
            ],
            options={
                'verbose_name': 'Odyssey',
                'verbose_name_plural': 'Odyssies',
                'db_table': 'odyssey',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requested_date', models.DateField(verbose_name='Requested Date')),
                ('is_accepted', models.BooleanField(blank=True, null=True, verbose_name='Is accepted')),
                ('odyssey', models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='odyssies', related_query_name='odyssey', to='web_app.odyssey', verbose_name='User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', related_query_name='request', to='web_app.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'requests',
            },
        ),
    ]
