# Generated by Django 5.0.4 on 2024-04-09 12:50

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Is Email verified'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='odyssey',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='odyssies', related_query_name='odyssey', to='web_app.odyssey', verbose_name='Odyssey'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True, verbose_name='OTP'),
        ),
    ]
